services:
  - type: web
    name: flowlite-core
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app --chdir . --bind 0.0.0.0:$PORT"
    autoDeploy: true
